### ISSUE TITLE
[TASK] MASA Blazor New document to-do list

### ISSUE THREAD

**Issue by codding-y** [masastack/MASA.Blazor#776]
### MASA Blazor新文档功能清单

以下是剩余的任务列表，这将每天更新，所以要注意变化。

The following is the list of remaining tasks, which will be updated daily, so pay attention to changes..

### 待办事项列表 (To Do List)

<hr />

- [x] 文档框架核心 (Document framework core)
- [x] 左侧导航 (Left Navigation)
  - [x] 导航内容 (Navigation content)
    - [x] 介绍 (Introduction)#826
    - [x] 快速入门 (Getting started)#826
    - [x] 特性 (Features)#826
    - [x] 样式和动画 (Styles and animations)#826
    - [x] 关于 (About)#826
  - [x] 功能和样式 (Function and style)
    - [ ] ~版本切换 (Version switching)~
    - [x] 样式还原  (Style Restore)#816
    - [x] 和顶部导航联动  (Linkage with top navigation)
    - [x] 国际化  (I18N)#819
    - [x] 导航标签  (Navigation label)#818
- [x] 顶部导航  (Top Navigation)
  - [x] 导航内容  (Navigation content)
    - [x] 文档中心 (Document center)
    - [x] 新手入门 (Getting started)
    - [x] Pro
    - [x] 博客 (Blog)
    - [x] 社区 (Community)
    - [x] 官网  (Official website)
    - [x] 开源地址链接 (Open source address link)
  - [x] 功能和样式 (Function and style)
    - [x] 样式还原 (Style Restore) #793 
    - [x] 和左侧导航联动 ()
    - [x] 导航标签 (Navigation label)
    - [x] #1125
    - [x] 语言切换 (Language switching)
    - [x] 设置 (Settings)
- [x] 右侧导航 (Right Navigation)
  - [x] 对接Github（issues）数据 (Docking Github (issues) data)#822
  - [x] 目录标签 (Catalog Label)
  - [x] 赞助商 (Sponsor)#822
  - [x] 样式还原 (Style Restore)#822

### UI组件

当满足以下条件时，组件文档被视为已完成：

- 每个组件API文档中的每个属性、事件、插槽等都有相应的描述并且API文档支持I18n切换。

The component document is considered completed when the following conditions are met:

- Each attribute, event, slot, etc. in each component API document has a corresponding description, and the API document supports I18n switching.
- [x] alerts #814
- [x] application
- [x] aspect-ratios
- [x] avatars
- [x] badges
- [x] banners
- [x] bars
  - [x] app-bars
  - [x] toolbars
  - [x] system-bars
- [x] block-text
- [x] borders
- [x] bottom-navigation
- [x] bottom-sheets
- [x] breadcrumbs
- [x] buttons
- [x] cards
- [x] carousels
- [x] chips
- [x] copyable-text
- [x] cron
- [x] dialogs
- [x] dividers
- [x] drag-zone
- [x] drawers
- [x] echarts
- [x] editor
- [x] error-handler
- [x] expansion-panels
- [x] floating-action-buttons
- [x] footers
- [x] form-inputs-and-ontrols
  - [x] autocomplete
  - [x] cascaders
  - [x] checkboxes
  - [x] file-inputs
  - [x] forms
  - [x] otp-input
  - [x] radio
  - [x] range-sliders
  - [x] selects
  - [x] sliders
  - [x] switches
  - [x] textareas
  - [x] text-fields
- [x] grids
- [x] groups
  - [x] button-groups
  - [x] chip-groups
  - [x] item-groups
  - [x] list-item-groups
  - [x] slide-groups
  - [x] windows
- [x] hover
- [x] icons
- [x] image-captcha
- [x] images
- [x] infinite-scroll
- [x] lists
- [x] markdown
- [x] menus
- [x] mobiles
  - [x] mobile-cascader
  - [x] mobile-date-pickers
  - [x] mobile-date-time-pickers
  - [x] mobile-pickers
  - [x] mobil-picker-views
  - [x] mobile-time-pickers
- [x] modals
- [x] navigation-drawers
- [x] not-grouped
- [x] overlays
- [x] pagination
- [x] Pickers
  - [x] date-pickers
  - [x] date-pickers-month
  - [x] time-pickers
- [x] popup-service
- [x] progress
  - [x] progress-circular
  - [x] progress-linear
- [x] ratings
- [x] sheets
- [x] skeleton-loaders
- [x] snackbars
- [x] steppers
- [x] subheaders
- [x] tables
  - [x] data-iterators
  - [x] data-tables
  - [x] simple-tables
- [x] tabs 
- [x] timelines
- [x] toast
- [x] tooltips
- [x] treeview
- [x] virtual-scroll

**Comment by capdiem** [comment]
@codding-y 对接github issue应精确到组件

**Comment by capdiem** [comment]
- [ ] 首页对移动端不友好
- [ ] 首页部分链接无法点击跳转，如MasaStack>权限中心>开发指南
- [ ] 首页TOC和锚点缺失
- [ ] 暗黑主题

**Comment by doddgu** [comment]
@codding-y 更新一下状态
